name: flutter_virtual_piano
description: A package for rendering an interactive virtual piano with Flutter.
version: 0.0.2
homepage: https://www.invisiblewrench.com

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0